#!/usr/bin/env Rscript


get_args <- function() {
    ### options: aggr
    option_list = list(
        optparse::make_option(c("-a", "--aggr"), action="store", default=NA, type="character", help="aggr.csv generated by make_aggregation_table()"),
        optparse::make_option(c("--tss"), action="store", default=4, type="numeric", help="TSS enrichment cutoff"),
        optparse::make_option(c("-o", "--output"), action="store", default="archr_metadata.tsv.gz", type="character", help="output file for metadata"),
        optparse::make_option(c("-g", "--gene-annotation"), action="store", default=NA, type="character", dest="gene_annotation", help="archr gene annotation (RDS)"))
    return(optparse::parse_args(optparse::OptionParser(option_list=option_list)))
}

run <- function(aggr, tss, output, gene_annotation=NA, help=FALSE) {
    require(ArchR)
    addArchRGenome("hg38")
    df = read.csv(aggr)
    if (is.na(gene_annotation) | !file.exists(gene_annotation)) {
        gene_annotation = getGeneAnnotation()
    } else {
        gene_annotation = readRDS(gene_annotation)
    }
    ArrowFiles = createArrowFiles(setNames(df$atac_fragments, df$library_id), minTSS=tss, geneAnnotation=gene_annotation)
    proj = ArchRProject(ArrowFiles, "ArchR", copyArrows=FALSE, geneAnnotation=gene_annotation)
    data.table::fwrite(getCellColData(proj), output, row.names=TRUE)
    unlink("ArchR", recursive=TRUE)
}

do.call(run, get_args())

